version: '3'
networks:
  development:
volumes:
  db_data:
  shared_data:
services:
  goldcup_db:
    image: mysql:8-debian
    container_name: mysql-goldcup
    restart: unless-stopped
    platform: linux/amd64
    networks:
      - development
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=goldcup
      - MYSQL_USER=goldcup
      - MYSQL_PASSWORD=goldcup
    ports:
      - 3306:3306

  goldcup_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: goldcup_api
    restart: unless-stopped
    depends_on:
      - goldcup_db
    volumes:
      - shared_data:/var/shared
      - ./:/app:rw
    networks:
      - development
    ports:
      - 3000:3000
    env_file: .env.development
